apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-constraints-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platformforge
    platformforge/env: prod
    platformforge/service: gatekeeper
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    notifications.argoproj.io/subscribe.on-sync-failed: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded: ""
spec:
  project: platform-prod

  sources:
    - repoURL: https://github.com/brianbeck/PlatformForge.git
      targetRevision: main
      path: platform/gatekeeper/constraints/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system

  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
