apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platformforge
    platformforge/env: prod
    platformforge/service: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    notifications.argoproj.io/subscribe.on-health-degraded: ""
    notifications.argoproj.io/subscribe.on-sync-failed: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded: ""
spec:
  project: platform-prod

  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: "39.0.7"
      helm:
        valueFiles:
          - $values/platform/traefik/base-values.yaml
          - $values/platform/traefik/overlays/prod/values.yaml

    - repoURL: https://github.com/brianbeck/PlatformForge.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
