---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCnW9+CYBNya30tXb/EUJwZftsiaYEwlUoM1eD6zvwllLpzlsmhxp7rekO+b+IwpfXfAxF7QTuz+5HEx5IW3QXyhnqX84QTrFlX/gBc0eqeulN/7jwmM9rj6wnqo1fe5criP1LuURIBQp66DNt2eW5Xmph7El4P7rHgKke4/MxRj0LJ7gDWIkbMwXIvU98I6viB/q1JEfjzcC5Sc21LP+OJbRKwn8PRxjXtXmeg7qpMUOlFFHoZyWDCwPvRxpG9UQmGVizsBqLvJgjKS/9+3g9z6q2qntGv8AgQTGy/Fi0ktJdjwjxKyuAxGeSVh6cxO2I/l7kib6fn0rt949vv5/GJSL4P1QWEqCtnEJNHLjvkiOgNOtZe+5VifdQhsaiZN7REAkeUhyEQ1VvrEwVHCuN6NtjEIEgO8ucd9/kNCWBoVh6aD7yslnY0O2EqPM5G/Gll5+OlNTQel61AcciP14yurzpiwmdmDVYoIoBd8P5vr+NEMswqEnzLVTXXqpOwNSFi6uVwUqaFZbmJpWJf7qQ3mpebTr+hG4VROPyw1rFQUcteoj2PgNLrcHzUGVxiWVPrZD+GvHwOVpzyVHoFF466XiTuE9H2v0lxCGfCprkso2nmEddb/79wjDtGOJwt5gAd2JpKqFXBOGNF4NeHwPl4v6QJDIbyYb12RQUnsGnFnAdCQdmExnbbSet0FkoREgz3BUbdgD+O3W7rSgDX6ZRWu+5ZstDN69NzSguyY42aShHQIznf7yNDTHzSR/4HK4fDdNDTQg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque