---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBbWJuySroyxUfgtbtMAqcOoAVvNtBNWw1+eNt0RsVMTkSvZ8n9nvpNpR4GQn5yZDPnU/hZ7AMFP+PEc9Mc21l7Kzrjk7fJnuVZbhC6loWDvb4qV0AR+PPFSsNX8cUvlVnJ167L0/EY14WWCJ2s4JkRUBNnOxov67ebqKmq+gWBjzvZIqvCYYO5MYs41cjrUngyL4lnSzLIo1WdClkveYJ466tGyKML5y+uZ44pJE2QIrAbG0P908cvb08MkDj/NTceYWGo3koL0bI17xyDmXGMVIKRPrQ+IPlavKTsDmzgnlJSgflN/4zAMu+gbT4KhESpOgtj5tsL7R3VyRYAgUt4AbFwjHSWXCEfDKm85WzWyMJADPD5T/RJhVcPpe2WVFjK5HICmTWWdyf3r8hRAmqyRZKwLLZX191ohrskNvOQaBLvp3pXR8pqvNDmNrk0noIEAMIfNOJT5w043wX+CgSPZzkIWKg959avr2BKzUDLHo0FmNEeeKjmX3xCP7rzIMTCQwOQzMLe+Z8dZhA3ff8DvTOjTyCbmMz3V7XfpYb9wFLoipMx8h8jadnDY3rxEFkrIb68/TGUfRqc7Z4RmADyWCIqKCsOoAuhCKnwCPbIh9u8GlCYtaCTjpKYNzCpQGfehAAN0KeWyCev66HMayVw4ZiUc1hY0Yjj3rHxADK2cMMRtCWnhQ3beUuyLM1bhQcZdxZ+BJCQmpmjkzRGEGoVgrnbNLxxcbu5/YiFGbhIcxb7tgLJMfeJeM1+MLXQoOuryRhhHQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque