---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCbPfFRza34XWiz8OWzU7wEMkTgCCJDk9y9p4ttz4kmWwN1B6QtkFwrEFXEvD9tHCO2k6lyg7ddexAo9lMQGNXSO/A9JBXJshiIivoi0/nyZLqawE9YuYmwbZWSH4Lye0Jq6+70/h8p2p+nxqFgYaJR+dbnUBsZv64FTonYOY/pIl3BIfyNPCUTiAvuj7P059PjyDuNbdKnC6CLrTx4MS1pNFgXGkLBn5fZE9jr3g/lzlA7I60m5bPQih8x4GTkPJAyI6qFT+29NK3X7ptUoE0meA/GwWliNJVfrNnavBSNLwRSIIcJD43rnlhGD/dLINNRaz+/ikmc9eJcCoU/hQXhlUF7TFrMYixeS3P2vK9VpfU+frmIhqkHMfBL4vV4ePU8pc99rOm6tb6Guxdk7tFh21wvEtRjDWnK/4SfS1FhEx3TgAba9CFEv6h9ooGV++7CHM4+4n6VDSym+Es1QB1F0iOJyzKRXVdTWujacPKGjEum+NCbiWHdGbSWj7E8SRxzgWkF60DAdEZQ2GyEtRC9WlTttr5j05jJflT8lh5tEfuAxc1o/Q46fIpVs0K54Kj10n+54HS6Hgpm1fRZ58hBInxzZ6RBOm5RBXVAz9ekKlefEF20e6KIMnRCcPRXfpaVHm1CuchwhLbceziSpuVr7RAPFi9Uxy629+xQNrnOAMHFrT3vswhD75fWG9IG2BmP6fwbTuApewv3jwc2yVtj5vuytguuJQqeiMrIPyCJONpyWs4xGcEPsKuB+aQd+qNCWjJjjQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
