# Traefik prod overlay

deployment:
  replicas: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

logs:
  general:
    level: WARN
  access:
    enabled: true
