---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBEZOMvWWuN9cF556lAvjnUvczwgkN1jo0b0BnslY0z/C8eBFbPrlfI3iT8XPNfchNW5+9Q4+js55ZIsmllIVfTzPK3TUWmvZ3I0rjArYd6ggYj1UqTDi1guv5wfXSuaAXV4yLwgaHt29RYoa2gDcKuraBfxPobYngca8e1IhOS4W4QpboP2eoZWcCvr0RgQtIxRrma9dvHuyKXNkkMyPzL0pSy7zJzwX73ltuEBOTYbuhsOyI6qExM+WV+74gmGOWDH87CKc1iQbcXShxs3uow0G6Rndak1mwPmF+Cjz0Jko23fhHIJdSx6qZPpqcAVp6p6GD9GKPn3x8kSFN8ZUQC4eZYKQ03bl99niFhdcLPyEJtIVxRS5dqxg+z42ON1ZMZ1bS0ABZYT/eDjWYquvtNwmWLxeyqaaa0o+7m97Z8hf3LlyeiH33FQTaEok5u3PGklqdu0RhsbEpOTcM1sjVKAfP5YFkpDKhc+NTAZxdkZPvWoiK16LDBrYpQ0fPCZPub2y0q67caLA8OrX+jRgoRncPEGt0J3v2NK3nPhmHQkjI69yY8ZpRrac13KAd2roHjYF95ib5JsY0HCNsAfU0Mymo6Ycl/ILNhLECYltQMWNP1ESTvjoH8JEpiLs0tgLvLDUcz6XEZE7Ov6UAoh+I2FXU3BoprePIm8uYJgG6SVGaqFt819jduEDTRgseGzib/gvDXCKqfMgyPttFBaJ7ARi4biItFRne0Pd0e+8xXoRVqJnN6vGKLQK1TRxg5VUHiyvd5Cg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque