---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBksIPRqypsWlRqfbZ+6mfNtiFfJz1PjyLhCDdlJIDsYV9+RDXzED/ptzmLWZUBx1jfuPLnqp5oKxOee66zUT2YkqSwCuInbvAK8yuFQZ6c6fZP1YdWThiKiS4w3IT/yKTGeLF43XaCzlEOC0cQCMiiuDlnj6ZIXgekQ/rHdQGbFE2qWEshIfbeuvu/lrk3FT/Req2KrC7i82++BGDSSrJcxvpQv+CtIdifNNRo0PBVIgfEvtupy0lMbEINtO7qvzlGRLusy0I4aKBanYyBWVegiNsOGkQWbtK5eLVbRsDvdRIG98d/fqKkEUUmgLGrb5FspmHDOVX15rjqnVYg8VHCH0BzKyxyMJq0+0QuGeG2oqI+d4kQmTY0WE0cpceGr7urc1CCc50D3Ul/TERBlZWXzJSRQrxg1fnihhOuvydYF8HKWeIoZz3XWIVEKinGUY/NrWF8DSj9rPOmVaUIhcvLx4Z3hfHF1TG0X+PLOeRcNl6tp4JgRsLf0kHurSywt12lczWWW26NEAiC9rlxnU16ds5MDN82eI0jk1vUVB91cYRD5c0ik50RcICyonfWd1Ddrzg80TegSp+qznBZIFSsFLhKmdsdjHMV/ItgnNqbgV4sH1AoL3ZvZuVFsChPLNI6v8FZNw0xOAtQabzZz5NsnWn0LyePoHNigFx+WIfO8VPrPXzHOCpK1IXbdft6KBj0AWmjMH+kTnSnDu8ah0SHLxbVG/BvmW+pA3BDBjsBZhWPWz9sxoYbjXS9Hbezo0MZ/kCxpw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque