---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC9GrA+4pURvpZ+wRYLO6LqV6+0oza3675c6W80uNGy2Qj6YzF1Rng/cPaQKkhkYx3/ROyv0aVhNsDYBfhoyFjWa5KXroK3Dw/QsrssWGuAQS0XNYHT1td0dMYPIpG2MMIILtKwY4u93Z3k2pnmv3OVovH2jJaqPM/+hbFWLFw9O+0CW+py5fwEU09zm2HAMkNVSJF7r2QMGmaIANLpanvJgAU23/FERit10V12Dd786n8KcuNhuBN+bqQwNgpYNggslT4aMyFOB5nmUL6xfGJyzQmF1gT4tDlnlvX/IxdvZP/stsQxT6/Vypx8KD+5bbYnx4Ndzqe4PAzD6UNJVHg8u4nFpW7H6wAc9CCo+G7oD/ZtAWcrl3g/obSHZvLOnE+Ov/lprBE8Cf96hpbOm59aOiNTolsK7gHvmtO8luNxT7DxmJ0ska2uA0JDqqLqaS3+brON+0I6LJDT9XoGuUKQTpax7H7KSBy3avxi92PVLfHuiUqTsvjkDvx9uq+Vhzl15RnC50XPLWJq6tiWEaRO2tLg0yY0G/j4U8tQDOlJMkgbYW9LMN2NE22qPNbAJuugs5Zfgy4spnnXLECUV90xBHfJXX4pf/bvzbT50zm/94i/C2CKcyF0Vk+A3lKHTJ6U3Su9uQW6WNi3QauSuON+qZyGpgE7BD4vZSQCHZ/OgmK/kmWmYZVOTMpl9PedwUyZD7SrOShsBOEIlh+ydcHKNzwmCXXOaNZxtQGq9d/HTl5SuVPtsbZDKNKLCZeZociF4/FlRQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
