"""Read/write environments.yml with Ansible blockinfile section markers."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from platformforge.models.environment import EnvironmentConfig

# Section markers matching Ansible's blockinfile format.
_INGRESS_BEGIN = "# BEGIN INGRESS CONFIGURATION"
_INGRESS_END = "# END INGRESS CONFIGURATION"
_NOTIFICATIONS_BEGIN = "# BEGIN NOTIFICATIONS CONFIGURATION"
_NOTIFICATIONS_END = "# END NOTIFICATIONS CONFIGURATION"
_SECRETS_BEGIN = "# BEGIN SECRETS CONFIGURATION"
_SECRETS_END = "# END SECRETS CONFIGURATION"


def find_project_root(start: Path | None = None) -> Path:
    """Walk up from *start* (default: cwd) to find the PlatformForge root.

    The root is identified by the presence of ``ansible/`` and ``platform/``
    directories.  Raises ``FileNotFoundError`` if not found within 10 levels.
    """
    current = (start or Path.cwd()).resolve()
    for _ in range(10):
        if (current / "ansible").is_dir() and (current / "platform").is_dir():
            return current
        parent = current.parent
        if parent == current:
            break
        current = parent
    raise FileNotFoundError(
        "Could not find PlatformForge project root (expected ansible/ and platform/ directories)"
    )


def find_env_root(start: Path | None = None) -> Path:
    """Find the platformforge-env repo root.

    Checks, in order:
    1. Current directory (if it has ``environments.yml`` or ``overlays/``)
    2. Sibling directory ``../platformforge-env`` relative to PlatformForge root
    3. Walk up from *start* looking for ``overlays/`` + ``argocd/``

    Raises ``FileNotFoundError`` if not found.
    """
    current = (start or Path.cwd()).resolve()

    # Check if we're already in the env repo
    if (current / "environments.yml").exists() or (current / "overlays").is_dir():
        return current

    # Check sibling of PlatformForge
    try:
        platform_root = find_project_root(start)
        sibling = platform_root.parent / "platformforge-env"
        if sibling.is_dir():
            return sibling
    except FileNotFoundError:
        pass

    # Walk up
    for _ in range(10):
        if (current / "overlays").is_dir() and (current / "argocd").is_dir():
            return current
        parent = current.parent
        if parent == current:
            break
        current = parent

    raise FileNotFoundError(
        "Could not find platformforge-env root. Expected environments.yml or overlays/ directory. "
        "Create it with: git clone <env-repo-url> ../platformforge-env"
    )


def env_path(env_root: Path | None = None) -> Path:
    """Return the path to environments.yml (in the env repo)."""
    root = env_root or find_env_root()
    return root / "environments.yml"


def load_config(path: Path) -> EnvironmentConfig | None:
    """Load and validate environments.yml.  Returns None if file missing."""
    if not path.exists():
        return None
    with open(path) as f:
        data = yaml.safe_load(f)
    if not data:
        return None
    return EnvironmentConfig(**data)


def load_raw(path: Path) -> dict[str, Any]:
    """Load environments.yml as a raw dict (no validation).  Returns {} if missing."""
    if not path.exists():
        return {}
    with open(path) as f:
        data = yaml.safe_load(f)
    return data or {}


def save_config(config: EnvironmentConfig, path: Path) -> None:
    """Write environments.yml in the exact format Ansible produces.

    Preserves section markers so that Ansible's ``blockinfile`` tasks
    can still update the file without duplicating sections.
    """
    lines: list[str] = []
    lines.append("# PlatformForge environment configuration")
    lines.append(
        f"# Generated by platformforge init on {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}"
    )
    lines.append("---")

    # Core section (no markers)
    lines.append(f'env_model: "{config.env_model}"')
    lines.append(f"single_cluster: {config.single_cluster}")
    lines.append(f"multi_cluster: {config.multi_cluster}")
    lines.append(f'stage_context: "{config.stage_context}"')
    lines.append(f'prod_context: "{config.prod_context}"')
    lines.append(f'stage_server: "{config.stage_server}"')
    lines.append(f'prod_server: "{config.prod_server}"')
    lines.append(f'platformforge_repo_url: "{config.platformforge_repo_url}"')
    lines.append(f'platformforge_repo_revision: "{config.platformforge_repo_revision}"')
    lines.append(f'env_repo_url: "{config.env_repo_url}"')
    lines.append(f'env_repo_revision: "{config.env_repo_revision}"')
    lines.append(f'env_repo_path: "{config.env_repo_path}"')

    # Ingress section
    lines.append(_INGRESS_BEGIN)
    lines.append(f"ingress_enabled: {config.ingress_enabled}")
    lines.append(f"traefik_enabled: {config.traefik_enabled}")
    lines.append(f'admin_email: "{config.admin_email}"')
    lines.append(f'base_fqdn: "{config.base_fqdn}"')
    lines.append(f'argocd_hostname_stage: "{config.argocd_hostname_stage}"')
    lines.append(f'argocd_hostname_prod: "{config.argocd_hostname_prod}"')
    lines.append(f"grafana_ingress_enabled: {config.grafana_ingress_enabled}")
    lines.append(f'grafana_hostname_stage: "{config.grafana_hostname_stage}"')
    lines.append(f'grafana_hostname_prod: "{config.grafana_hostname_prod}"')
    lines.append(f"prometheus_ingress_enabled: {config.prometheus_ingress_enabled}")
    lines.append(f'prometheus_hostname_stage: "{config.prometheus_hostname_stage}"')
    lines.append(f'prometheus_hostname_prod: "{config.prometheus_hostname_prod}"')
    lines.append(f'alertmanager_hostname_stage: "{config.alertmanager_hostname_stage}"')
    lines.append(f'alertmanager_hostname_prod: "{config.alertmanager_hostname_prod}"')
    lines.append(f"rollouts_ingress_enabled: {config.rollouts_ingress_enabled}")
    lines.append(f'rollouts_hostname_stage: "{config.rollouts_hostname_stage}"')
    lines.append(f'rollouts_hostname_prod: "{config.rollouts_hostname_prod}"')
    lines.append(f"pihole_enabled: {config.pihole_enabled}")
    lines.append(f'pihole_primary_ip: "{config.pihole_primary_ip}"')
    lines.append(f'pihole_secondary_ip: "{config.pihole_secondary_ip}"')
    lines.append(_INGRESS_END)

    # Logging section
    lines.append("# BEGIN LOGGING CONFIGURATION")
    lines.append(f'loki_url: "{config.loki_url}"')
    lines.append("# END LOGGING CONFIGURATION")

    # Notifications section
    lines.append(_NOTIFICATIONS_BEGIN)
    lines.append(f'notification_provider: "{config.notification_provider}"')
    lines.append(f'slack_channel_stage: "{config.slack_channel_stage}"')
    lines.append(f'slack_channel_prod_critical: "{config.slack_channel_prod_critical}"')
    lines.append(f'slack_channel_prod_warnings: "{config.slack_channel_prod_warnings}"')
    lines.append(f'slack_channel_security: "{config.slack_channel_security}"')
    lines.append(f'slack_channel_vulnerabilities: "{config.slack_channel_vulnerabilities}"')
    lines.append(f'smtp_host: "{config.smtp_host}"')
    lines.append(f'smtp_from: "{config.smtp_from}"')
    lines.append(f'smtp_to: "{config.smtp_to}"')
    lines.append(_NOTIFICATIONS_END)

    # Secrets section
    lines.append(_SECRETS_BEGIN)
    lines.append(f'secrets_strategy: "{config.secrets_strategy}"')
    lines.append(f'vault_address: "{config.vault_address}"')
    lines.append(_SECRETS_END)

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
